config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  match '/portfolio',  to: 'static_pages#portfolio',            via: 'get'
  match '/connect',  to: 'static_pages#connect',            via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def portfolio
  end

  def connect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar">
	<div class="navbar-title animated fadeInDown">
		<div class="picture-placeholder"></div>
		<h1>John Donner</h1>
	</div>
	<div class="main-navbar-inner">
		<div class="container">
			<div class="nav">
				<li class="nav-item animated flipInX"><%= link_to "Home",		root_path %></li>
				<li class="nav-item animated flipInX"><%= link_to "Portfolio",		portfolio_path %></li>
			</div>
			<div class="nav-right">
				<li class="nav-item animated flipInX"><%= link_to "Twitter",		"https://twitter.com/JohnBDonner", class: "link-twitter", :target => "_blank" %></li>
				<li class="nav-item animated flipInX"><%= link_to "Github",		"https://github.com/JohnBDonner", class: "link-github",  :target => "_blank" %></li>
				<li class="nav-item animated flipInX"><%= link_to "LinkedIn",		"https://linkedin.com/in/johnbdonner", class: "link-linkedin", :target => "_blank" %></li>
			</div>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>JohndonnerSite</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="content"><%= yield %></div>
		<div class="pic-view-bg"></div>
	</body>
</html>

app/views/static_pages/home.html.erb
<p>I am an optimistic developer, designer and entrepreneur. Creating products that combine aesthetics and function, where engineering meets design, is a passion of mine. I tend to have incredibly high standards for the work that I do; I try to set the bar just under impossible.</p>
<p>I love larger-than-life things, including but not limited to: epic sounding chordal progressions, success stories and projects that leave a positive impact on the masses. If you would like me to be a part of your world-shattering idea, drop me a line at one of the social links above.</p>
<p>When I'm not coding, I'm reading, brainstorming, producing music, djing or socializing.</p>

app/views/static_pages/portfolio.html.erb
<div class="portfolio-item">
	<div class="portfolio-content image">
		<%= image_tag("sparksite-logo.png", :size => "200x200", :alt => "sparksite") %>
	</div>
	<div class="portfolio-content description">
	<h3>Spark Entrepreneurs</h3>
	<p>The website for the official undergraduate entrepreneurship club at the University of Rochester. Developed and designed on Ruby on Rails.</p>
	</div>
	<div class="portfolio-content links">
		<li><%= link_to "View on Github", 			"https://github.com/sparkentrepreneurship/Spark-Site", class: "link-github", :target => "_blank" %></li>	
	</div>
</div>
<div class="portfolio-item" style="animation-delay: 2s;">
	<div class="portfolio-content image">
		<%= image_tag("210-picture.png", :size => "200x200", :alt => "csc 210 project") %>
	</div>
	<div class="portfolio-content description">
	<h3>CSC 210 Project</h3>
	<p>A web application built with the standard ruby language, sqlite3 and AJAX. Users submit links that they think are good resources or sites for a given topic, and through upvotes, organizes this data to show the best of the internet.</p>
	</div>
	<div class="portfolio-content links">
		<li><%= link_to "View on Github", 			"https://github.com/JohnBDonner/csc210-project", class: "link-github", :target => "_blank" %></li>
	</div>
</div>
<div class="portfolio-item" style="animation-delay: 3s;">
	<div class="portfolio-content image">
		<%= image_tag("UR Vocal Coach Icon.png", :size => "200x200", :alt => "vocal coach") %>
	</div>
	<div class="portfolio-content description">
	<h3>UR Vocal Coach</h3>
	<p>An android application that helps singers easily practice, whether outside of a lesson or before a performance. Two modes were developed to train pitch identification and pitch-stable crescendos.</p>
	</div>
	<div class="portfolio-content links">
		<li><%= link_to "View on Github", 			"https://github.com/UR-Vocal-Coach/app", class: "link-github", :target => "_blank" %></li>
		<li><%= link_to "View Site", 				"https://sites.google.com/a/u.rochester.edu/ur-vocalcoach/", :target => "_blank" %></li>
	</div>
</div>
<div class="portfolio-item" style="animation-delay: 4s;">
	<div class="portfolio-content image">
		<%= image_tag("bucket-logo.png", :size => "200x200", :alt => "travel app") %>
	</div>
	<div class="portfolio-content description">
		<h3>Bucket</h3>
		<p>Mock web and mobile designs for a concept travel application.</p>
	</div>
	<div class="portfolio-content links">
		<li><%= link_to "View Screens", 			"#", id: "view-bucket" %></li>
	</div>
	<div class="full-pictures" id="bucket">
		<li class="1 pic"><%= image_tag "bucket_web.png" %></li>
		<li class="2 pic"><%= image_tag "bucket_mobile.png" %></li>
	</div>
</div>
<div class="footer">
	John Donner | 2015
</div>